---
language: python

services:
  - docker

before_install:
  # Upgrade Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  # Build the image
  - docker build -t docker-ansible .
  # Run a container from the image
  - docker run -d --name ansible-container --privileged docker-ansible
  # Verify Ansible
  - docker exec -it ansible-container ansible --version
  # Verify systemctl
  - docker exec -it ansible-container systemctl list-units
